# Generated by Django 4.2.5 on 2024-02-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CollegeAdmin',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_college_name', models.CharField(blank=True, max_length=50, null=True)),
                ('a_contact_number', models.IntegerField(blank=True, null=True)),
                ('a_logo', models.CharField(blank=True, max_length=200, null=True)),
                ('a_email', models.CharField(blank=True, max_length=40, null=True)),
                ('a_password', models.CharField(blank=True, max_length=40, null=True)),
                ('a_location', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'college/admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyTable',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(blank=True, max_length=30, null=True)),
                ('c_industry', models.CharField(blank=True, max_length=100, null=True)),
                ('c_logo', models.CharField(blank=True, max_length=100, null=True)),
                ('c_email', models.CharField(blank=True, max_length=50, null=True)),
                ('c_contact_number', models.IntegerField(blank=True, null=True)),
                ('c_password', models.CharField(blank=True, max_length=40, null=True)),
                ('c_location', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'company_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PsReport',
            fields=[
                ('ps_id', models.AutoField(primary_key=True, serialize=False)),
                ('ps_date', models.DateField(blank=True, null=True)),
                ('ps_performance', models.CharField(blank=True, max_length=300, null=True)),
                ('ps_status', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'ps_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentList',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_f_name', models.CharField(blank=True, max_length=20, null=True)),
                ('s_m_name', models.CharField(blank=True, max_length=20, null=True)),
                ('s_l_name', models.CharField(blank=True, max_length=20, null=True)),
                ('s_phone_number', models.IntegerField(blank=True, null=True)),
                ('s_email', models.CharField(blank=True, max_length=30, null=True)),
                ('s_password', models.CharField(blank=True, max_length=30, null=True)),
                ('s_address_permanent', models.CharField(max_length=300)),
                ('s_address_temporary', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'student_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentQualifications',
            fields=[
                ('sq_id', models.AutoField(primary_key=True, serialize=False)),
                ('sq_degree_name', models.CharField(blank=True, max_length=30, null=True)),
                ('sq_institute_name', models.CharField(blank=True, max_length=30, null=True)),
                ('sq_graduation_year', models.DateField(blank=True, null=True)),
                ('sq_cgpa', models.FloatField(blank=True, db_column='sq_CGPA', null=True)),
            ],
            options={
                'db_table': 'student_qualifications',
                'managed': False,
            },
        ),
    ]
