# Generated by Django 4.2.5 on 2024-03-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCollege',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_college_name', models.CharField(blank=True, max_length=50, null=True)),
                ('a_contect_number', models.IntegerField(blank=True, null=True)),
                ('a_logo', models.CharField(blank=True, max_length=100, null=True)),
                ('a_email', models.CharField(blank=True, max_length=70, null=True)),
                ('a_password', models.CharField(blank=True, max_length=50, null=True)),
                ('a_location', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'admin_college',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(blank=True, max_length=50, null=True)),
                ('c_industry', models.CharField(blank=True, max_length=40, null=True)),
                ('c_logo', models.CharField(blank=True, max_length=100, null=True)),
                ('c_email', models.CharField(blank=True, max_length=50, null=True)),
                ('c_password', models.CharField(blank=True, max_length=40, null=True)),
                ('c_contact_number', models.IntegerField(blank=True, null=True)),
                ('c_location', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_f_name', models.CharField(blank=True, max_length=20, null=True)),
                ('s_m_name', models.CharField(blank=True, max_length=20, null=True)),
                ('s_l_name', models.CharField(blank=True, max_length=20, null=True)),
                ('s_phone_number', models.IntegerField(blank=True, null=True)),
                ('s_email', models.CharField(blank=True, max_length=40, null=True)),
                ('s_password', models.CharField(blank=True, max_length=40, null=True)),
                ('s_address_permanent', models.CharField(max_length=300)),
                ('s_address_temporary', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CollegeAdmin',
        ),
        migrations.DeleteModel(
            name='CompanyTable',
        ),
        migrations.DeleteModel(
            name='StudentList',
        ),
        migrations.DeleteModel(
            name='StudentQualifications',
        ),
    ]
