# Generated by Django 4.2.5 on 2024-03-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0002_admincollege_company_student_delete_collegeadmin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_email', models.CharField(blank=True, max_length=40, null=True)),
                ('e_password', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationTable',
            fields=[
                ('ap_id', models.AutoField(primary_key=True, serialize=False)),
                ('ap_date', models.DateField(blank=True, null=True)),
                ('ap_status', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'application_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyRegistration',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(blank=True, max_length=100, null=True)),
                ('c_industry', models.CharField(blank=True, max_length=60, null=True)),
                ('c_email', models.CharField(blank=True, max_length=50, null=True)),
                ('c_url', models.CharField(blank=True, db_column='c_URL', max_length=100, null=True)),
                ('c_location', models.CharField(blank=True, max_length=450, null=True)),
            ],
            options={
                'db_table': 'company_registration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlacementDetails',
            fields=[
                ('pd_id', models.AutoField(primary_key=True, serialize=False)),
                ('pd_title', models.CharField(blank=True, max_length=40, null=True)),
                ('pd_description', models.CharField(blank=True, max_length=500, null=True)),
                ('pd_position', models.CharField(blank=True, max_length=40, null=True)),
                ('pd_qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('pd_salary_or_package', models.IntegerField(blank=True, null=True)),
                ('pd_required_people', models.IntegerField(blank=True, null=True)),
                ('pd_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'placement_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentQualification',
            fields=[
                ('sq_id', models.AutoField(primary_key=True, serialize=False)),
                ('sq_ssc_total_marks', models.IntegerField(blank=True, null=True)),
                ('sq_ssc_obtained_marks', models.IntegerField(blank=True, null=True)),
                ('sq_hsc_total_marks', models.IntegerField(blank=True, null=True)),
                ('sq_hsc_obtained_marks', models.IntegerField(blank=True, null=True)),
                ('sq_hsc_percentage', models.FloatField(blank=True, null=True)),
                ('sq_bachelor_cgpa', models.FloatField(blank=True, db_column='sq_bachelor_CGPA', null=True)),
                ('sq_bachelor_percentage', models.FloatField(blank=True, null=True)),
                ('sq_bachelor_degree', models.CharField(blank=True, max_length=40, null=True)),
                ('sq_bachelor_university', models.CharField(blank=True, max_length=60, null=True)),
                ('sq_master_sem_1', models.FloatField(blank=True, null=True)),
                ('sq_master_sem_2', models.FloatField(blank=True, null=True)),
                ('sq_master_sem_3', models.FloatField(blank=True, null=True)),
                ('sq_master_sem_4', models.FloatField(blank=True, null=True)),
                ('sq_9th_percentage', models.FloatField(blank=True, null=True)),
                ('sq_11th_percentage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student_qualification',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AdminCollege',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
