# Generated by Django 4.2.5 on 2024-03-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0003_admin_applicationtable_companyregistration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cource',
            fields=[
                ('cource_id', models.AutoField(primary_key=True, serialize=False)),
                ('cource_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'cource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
    ]
